### ISSUE TITLE
Formtastic 4.0

### ISSUE THREAD

**Issue by mikz** [formtastic/formtastic#1197]
New release of Formtastic is coming. https://github.com/justinfrench/formtastic/pull/1108#issuecomment-187905777

Major changes will be:
- [x] dropping support for Rails 3 and Rails 4.0  (#1108)
- [x] support for Rails 5 Attributes API (#1188)
- [x] eager load to prevent errors in concurrent environments (#1196)
- [x] removal of deprecated finder methods (#1139)
# TODO
- [x] release 3.1.4 #1198
- [x] merge #1108
- [x] merge #1139 
- [x] merge #1196
- [x] merge `4.0-dev` to master
- [x] switch 4.0 work to master
- [x] reevaluate [4.0 beta milestone](https://github.com/justinfrench/formtastic/milestone/27) 
- [x] add more tasks
- [x] release 4.0 beta
- [ ] release 4.0 rc
- [ ] release 4.0

**Comment by voyera** [comment]
Just have to say keep up the good work guys, this is great!

**Comment by javierjulio** [comment]
@mikz in your first todo list, it seems that "support for Rails 5 Attributes API (#1188)" should be marked completed since PR was merged. Is a v4 release of Formtastic still planned? Anyone pushing that through or has effort died out?

**Comment by mikz** [comment]
@javierjulio thanks for checking. Marked it as done. 

It was just me pushing through and I could not find the time lately. I guess 

What would help is someone trying the git branch and checking if there are any issues with the upgrade. Then we could mark the beta release I guess.

**Comment by javierjulio** [comment]
@mikz I'm asking since myself and a few others are new maintainers of ActiveAdmin. Formtastic gem is pretty important to us so we'd like to see it continue or look for a new solution. It seems the work is here it just needs some attention and a release. One of the last PR's you took was from @Fivell who is also an ActiveAdmin maintainer.

I set Formtastic to master branch on AA locally, ran our test suite and everything is green. 👍🏻 I will do more testing with our sample app which has various form setups and that should really test Formtastic v4. How else can we help to get a release out? 

While its possible to modify the wrapping HTML of inputs, the fieldset/list wrapper is a problem. Would you also consider a change to make it easier to override the fieldset and list wrapper HTML output? Right now its in a module but done in a long method without a way of doing it. It would be helpful to have a way of modifying the HTML for all in v4 even if it means subclassing all inputs.

**Comment by mikz** [comment]
@javierjulio I see there was a 1.0 release of ActiveAdmin, finally. I'd like to try to do normal beta releases of formtastic that would match releases of AA, so we don't have to target git, but just prerelease gem version.

I wanted to make it a bit bigger release and pack more stuff into it, but that sounds harder and harder, so we might just release what is there now.

I agree that customising the structure of generated forms should have a better story. I'm happy to see some examples on how that should work.

Kind of unrelated PR, but similar approach was https://github.com/justinfrench/formtastic/pull/1211. Having examples on how to use it and some prototype implementation would be nice so we can see how that would be used by people and affect the core.

I'd definitely want to go through opened PRs and see what makes sense to try to get merged. Maybe not in the first beta release, but at least try to get it in later. There is a milestone https://github.com/justinfrench/formtastic/milestone/27 with issues I hoped we could get into beta release. We can do first beta with what is there now and then second one later.

Right now only @justinfrench can do a release (https://github.com/justinfrench/formtastic/issues/1163). So I think this might be good time to try to share those permissions, so I can do beta releases more often.

**Comment by dkniffin** [comment]
@mikz @justinfrench How is 4.0 going? My PR #1272 got merged about 6 months ago, and I'm still pointing a project at my fork. I'd love to get it pointing to 3.2 or 4.0 instead.

**Comment by mikz** [comment]
@dkniffin I understand that, but it is not going at all. I'm not actively using this project, so it is hard for me to work on it without any testing ground.

We could try to release beta1 at least. WDYT @justinfrench? That would remove the git dependency and at least move us forward a bit, even when it would not be feature complete.

**Comment by justinfrench** [comment]
Hey folks, sorry for the lack of inactivity. @deivid-rodriguez has been helping get master ready for a 4.0. I've released a 4.0.0.rc1 gem today, and I'm actively looking for new maintainers.
